### PR TITLE
Change reset setting value icon

### PR DESCRIPTION
**Pull request by dersnek**
Currently, a button to reset setting value looks like a refresh button.
Sometimes it gets me thinking that it's a refresh button, to get the currently set value, while it actually resets it to the default value.

reset_icon_before

This new icon makes it a bit more clear that it's button which causes destructive change.

reset_icon_after

Same spinning animation for when it's pressed still looks ok with this new icon.

### CODE REVIEW

**Comment by vinistock** [comment]
Thanks for the contribution! I think this makes sense to avoid confusion with refreshing, but I wonder if an X is the ideal substitute - as it could also be confused with a delete button.

What's your opinion on a [single circular arrow](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn0.iconfinder.com%2Fdata%2Ficons%2Farrow-set-4%2F100%2FUntitled-1-60-512.png&f=1&nofb=1) or a rewind icon? (we can remove the spinning animation if needed of course).

**Comment by dersnek** [comment]
> 
> 
> Thanks for the contribution! I think this makes sense to avoid confusion with refreshing, but I wonder if an X is the ideal substitute - as it could also be confused with a delete button.
> 
> What's your opinion on a [single circular arrow](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn0.iconfinder.com%2Fdata%2Ficons%2Farrow-set-4%2F100%2FUntitled-1-60-512.png&f=1&nofb=1) or a rewind icon? (we can remove the spinning animation if needed of course).

Makes sense to me, this icon is even better. Totally forgot it exists! Changed to [this](https://fontawesome.com/icons/undo?style=solid) and reversed animation direction.

**Comment by dersnek** [comment]
Also made animation a bit quicker so that it spins 360 degrees before the `.active` class is removed :)

**Review by vinistock — APPROVED** [review]
Amazing! Thank you for the contribution.  Be sure to add an entry to the changelog and we can merge

**Comment by dersnek** [comment]
> 
> 
> Amazing! Thank you for the contribution. Be sure to add an entry to the changelog and we can merge

Sure, does this work? Thank you for reviewing it and suggesting a better icon :)

**Comment by vinistock** [comment]
That looks good. Thanks again!

**Pull request merged**
