### PR TITLE
Allow extra params in settings and profiles controllers

### PR DESCRIPTION
**Pull request by denny**
* Allow :_method and :locale params in settings controller
* Allow :locale param in profiles controller

### CODE REVIEW

**Comment by denny** [comment]
I guess these are new to Rails 6.1 maybe?

**Comment by vinistock** [comment]
Once again, thank you so much for the interest and help with Sail.

I think this PR should be merged regardless, since the strong parameters aren't including all that's needed. However, I couldn't quite reproduce the issue with Rails 6.1.1. I get the warnings in the console about unpermitted params, but requests are successful.

Did you verify that this fixes the issue?

**Comment by denny** [comment]
Hrm. It did for me, but maybe it's tangled up with the app I'm embedding Sail into. I'll try to isolate things a bit more if I get a chance later this week coming.

**Comment by vinistock** [comment]
Well, if it fixes the issue, I'm fine with merging. We should fix the unpermitted parameters anyway.

**Comment by denny** [comment]
Having looked at my own forms again, I think there might be a more 'correct' way of fixing this, but it involves a bit more work. Leave this open for now and I'll see if I can tackle it in the next week or two? I think Sail might need to move from `form_tag` to `form_for` or `form_with`, and then you can use a `.require().permit()` chain in the receiving methods instead of just `.permit()`, which will handle the authenticity token param automatically. I haven't seen a locale param in my forms though, is that a part of Sail?

**Comment by vinistock** [comment]
Sounds good. Sail will handle the locale parameter, as long as the main app passes it along.

**Comment by denny** [comment]
By the way, in case you're interested, here's a screenshot of Sail embedded into the ShinyCMS admin area 🙂 
Screenshot from 2021-01-18 22-08-42

**Comment by vinistock** [comment]
That looks fancy. I love it!

**Pull request merged**
